In [1]:
import numpy as np


# Custom implementation of min_max_scaler

In [21]:
def min_max(x):
    j=0
    x_min = array.min() #taking min of the array
    x_max = array.max() #taking max of the array
    for ele in x: 
        x_new = (ele - x_min)/(x_max-x_min) # calculating normalized value for each element in array
        x[j]=x_new #replacing each element with new calculated value 
        j+=1
    return x

    

In [22]:
array = np.array([2,3,4,5,68,9,5,3,3,57,80,33.45,4]).reshape(-1,1)
y = min_max(array)
y

array([[0.        ],
       [0.01282051],
       [0.02564103],
       [0.03846154],
       [0.84615385],
       [0.08974359],
       [0.03846154],
       [0.01282051],
       [0.01282051],
       [0.70512821],
       [1.        ],
       [0.40320513],
       [0.02564103]])

# Sklearns implementation

In [19]:
from sklearn.preprocessing import MinMaxScaler
array = np.array([2,3,4,5,68,9,5,3,3,57,80,33.45,4]).reshape(-1,1)
transformer = MinMaxScaler().fit(array)
transformer.transform(array)

array([[0.        ],
       [0.01282051],
       [0.02564103],
       [0.03846154],
       [0.84615385],
       [0.08974359],
       [0.03846154],
       [0.01282051],
       [0.01282051],
       [0.70512821],
       [1.        ],
       [0.40320513],
       [0.02564103]])

# custom implementation in python

In [10]:
import math
def stanrdadize(x):
    j=0
    z=0
    N=len(x)
    mean = x.sum()/(N) #mean calculation
    for ele in x:
        z += (ele-mean)**2
    std = np.sqrt(z/N) #standard deviation
    for ele in x:   
        x[j]= (ele-mean)/std #calculation of standardization value (xi-mean/std)
        j+=1
    return x

In [12]:
array = np.array([2,3,4,5,68,9,5,3,3,57,80,33.45,4]).reshape(-1,1)
out = stanrdadize(array)
out

array([[-0.70502562],
       [-0.66843016],
       [-0.6318347 ],
       [-0.59523924],
       [ 1.71027477],
       [-0.4488574 ],
       [-0.59523924],
       [-0.66843016],
       [-0.66843016],
       [ 1.30772471],
       [ 2.1494203 ],
       [ 0.44590161],
       [-0.6318347 ]])

# Sklearn Implementation

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
array = np.array([2,3,4,5,68,9,5,3,3,57,80,33.45,4]).reshape(-1,1)
scaler.fit_transform(array)

array([[-0.70502562],
       [-0.66843016],
       [-0.6318347 ],
       [-0.59523924],
       [ 1.71027477],
       [-0.4488574 ],
       [-0.59523924],
       [-0.66843016],
       [-0.66843016],
       [ 1.30772471],
       [ 2.1494203 ],
       [ 0.44590161],
       [-0.6318347 ]])